# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WiFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WiFinder
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'RxSwiftUtilities'
end

target 'WiFinderTests' do
  pod 'RxBlocking', '~> 4.0'
  pod 'RxTest',     '~> 4.0'
end
